additional:
  - "kong-openssl"
  - "kong-runtime"

files:
  - "!.gitignore"
  - "!.github/template-sync.yml"
  - "!.pre-commit-config.yaml"
  - "!Makefile"
  - "!.github/dependabot.yml"
  - "!.github/workflows/sync.yaml"
  - "!.github/workflows/release.yml"
  - "!.releaserc"
  - "!build.sh"
  - "!test.sh"
  - "!.env"
  - "!Dockerfile"
