name: Pull Request Auto Updater

on:
  push:
    branches:
    - main
    - fix/update-prs

jobs:
  update-pull-requests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Update ALL THE PRS! 🎉
        uses: castastrophe/actions-pr-auto-update@v1.1.0
        with:
          token: ${{ steps.app-token.outputs.token }}
          limit: 10
          include_drafts: true
